
version: 2

models:
  - name: v_stg_customers
    description: "raw staging customers data"
    columns:
      - name: customer_id
        description: ""
        tests:
          - unique
          - not_null
      - name: company_name
        description: ""
      - name: contact_name
        description: ""
      - name: contact_title
        description: ""
      - name: address
        description: ""
      - name: city
        description: ""
      - name: region
        description: ""
      - name: postal_code
        description: ""
      - name: country
        description: ""
      - name: phone
        description: ""
      - name: fax
        description: ""

